AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS_Secrets_Manager_lambda1

  Sample SAM Template for AWS_Secrets_Manager_lambda1

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  SecretsManagerARNParameter:
    Type: String
    Default: "arn:aws:secretsmanager:ap-northeast-1:750031788220:secret:tutorials/MyFirstTutorialSecret-jBJka5"
    Description: Enter AWS Secrets Manager ARN for SecretTestFunction

Resources:
  SecretTestFunction:
    Type: AWS::Serverless::Function
    # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: secret_test/
      Handler: app.lambda_handler
      Runtime: python3.6
      Environment:
        Variables:
          SM1ID: !Select [0, !Split ["-", !Select [6, !Split [":", !Ref SecretsManagerARNParameter]]]]
          SM1Region: !Select [3, !Split [":", !Ref SecretsManagerARNParameter]]
      Policies:
      - AWSSecretsManagerGetSecretValuePolicy:
          SecretArn: !Ref SecretsManagerARNParameter
      Events:
        SecretTest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /secret
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/secret/"
  SecretTestFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SecretTestFunction.Arn
  SecretTestFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SecretTestFunctionRole.Arn
